#!/bin/bash

# takes input of a URL 
# $1=URL http - where a media clip is found, the end of the URL after "/" is the file to be converted to CAI.
# accepts as input .wav .mp4 .m4a .aac e.g: $1 = http://www.videoload.de/myfile.aac
# returns the file in cai format

# get the filename after the last "/" in e.g. $1 = http://www.videoload.de/myfile.aac
# result in $file = myfile.aac
file=${1##*/};

echo $1 >> /var/www/clips/LOG ;

# load the file and put it in the working directory /home/nonnen/TV/WWW/Mobile/clips/
wget -q $1 -O /var/www/clips/$file 2 >> /var/www/clips/LOG;
chmod 755 /var/www/clips/$file;

# convert to PCM 48K
# 48K version: 
vlc -I dummy "/var/www/clips/${file}"  --verbose=1 --file-logging --logfile=vlc.log --sout "#transcode{vcodec=none,acodec=s16le,channels=1,samplerate=48000}:file{mux=raw,dst=/var/www/clips/${file}.pcm}" vlc://quit 2> /dev/null;
# /usr/bin/ffmpeg -i /var/www/clips/$file -ac 1 -acodec pcm_s16le -ar 48000 /var/www/clips/$file.pcm 2> /dev/null;

# Run PCM 2 CAI conversion
# 48Kversion
/home/ubuntu/bin/pcm2cai /var/www/clips/$file.pcm /var/www/clips/$file.cai > /dev/null ;
chmod 755 /var/www/clips/$file.cai;

#remove all the crap from working directory
 rm -f /var/www/clips/$file.cai ;
 rm -f /var/www/clips/$file.pcm ;
 rm -f /var/www/clips/$file ;

#echo "clips/"$file".cai";
cat /var/www/clips/$file.cai

