#!/bin/bash

# takes input of a URL and transcodes to mp4
# file has to be already in the directory /var/www/clips ! (cai conversion had been done BEFORE !)
# after transcode the mp4 file is found in /var/www/mp4

# $1=URL http - where a media clip is found, the end of the URL after "/" is the file to be converted to CAI.
# accepts as input .wav .mp4 .m4a .aac e.g: $1 = http://www.videoload.de/myfile.aac
# returns the file in cai format

# get the filename after the last "/" in e.g. $1 = http://www.videoload.de/myfile.aac
# result in $file = myfile.aac
file=${1##*/};

echo "new fmp4 conv.:"$file >> /var/www/mp4/LOG ;

# Run ffmpeg
ffmpeg -y -i /var/www/clips/$file -s 432x320 -b 384k -vcodec libx264 -flags +loop+mv4 -movflags faststart -cmp 256 -partitions +parti4x4+parti8x8+partp4x4+partp8x8 -subq 6 -trellis 0 -refs 5 -bf 0 -coder 0 -me_range 16 -g 250 -keyint_min 25 -sc_threshold 40 -i_qfactor 0.71 -qmin 10 -qmax 51 -qdiff 4 -c:a aac -strict -2 -ac 1 -ar 16000 -r 13 -ab 32000 -aspect 3:2 /var/www/mp4/$file.mp4
# ffmpeg -y -i /var/www/clips/$file -s 432x320 -b 384k -vcodec libx264 -flags +loop+mv4 -movflags faststart -cmp 256 -partitions +parti4x4+parti8x8+partp4x4+partp8x8 -subq 6 -trellis 0 -refs 5 -bf 0 -coder 0 -me_range 16 -g 250 -keyint_min 25 -sc_threshold 40 -i_qfactor 0.71 -qmin 10 -qmax 51 -qdiff 4 -acodec libfdk_aac -ac 1 -ar 16000 -r 13 -ab 32000 -aspect 3:2 /var/www/mp4/$file.mp4 2> /dev/null;

chmod 755 /var/www/mp4/$file.mp4;

#remove all the crap from working directory
# XXX rm /home/nonnen/TV/WWW/Mobile/clips/$file ;
# XXX rm /home/nonnen/TV/WWW/Mobile/clips/$file.wav ;

#output acces link ;
echo "http://d-gp2-tocai-1.imovetv.com/mp4/"$file".mp4" ;

