#!/bin/bash

# sets a lock - rusn exclusively one time at the sam time
# treats incoming ftpo files
#
#  runs every hour



LOCK_FILE="/var/www/logs/pngcode_lock" ;

# set that MUTEX in case of calls coming to this SCRIPT WHEN NOT YET FINISHED
if [ -f $LOCK_FILE ];
then
	echo "LOCK SET in /var/www/logs/ can't do anything"
   exit ;
else
   touch $LOCK_FILE ; 
   chmod 777 $LOCK_FILE ; 
fi

# local target dir
pushd /var/www ;

	# STEP 1 - DO WE HAVE NEW FILES ? == .mp4 doesn't exist yet.
        # ==============================

	# get the full list of all files
	dd=(`echo "ls -1 *.mpg" | sudo sftp -i /home/ubuntu/.ssh/jn_dev2.pem dishads@d-gp2-sftp-1.imovetv.com | sort`) ; 
	nr=${#dd[@]} ;
	j=0 ;
	txt=0 ;
	# echo "Number files total" $nr ;
	while [ "$j" -lt "$nr" ] ; 
	do

# echo "analyzing" ${dd[$j]} ;
		clipbase=`basename "${dd[$j]}" .mpg`
		# does that file have a pitcure folder in png already ?
        	if [ -d  "./png/${clipbase}" ] ;
        	then
                	# do nothing - png folder exists already
# echo " png folder exists already - we assume pictures do, too!"
			(( txt = txt + 1 )) ;
        	else
# echo " generating pngs "
			# let's make the remote and the local folder and go in there
			echo "mkdir ./png/${clipbase}" | sudo sftp -i /home/ubuntu/.ssh/jn_dev2.pem dishads@d-gp2-sftp-1.imovetv.com	;		
			mkdir "./png/${clipbase}" ; chmod 777 "./png/${clipbase}" ;
			pushd "./png/${clipbase}" ;

			# get the original, since here is a folder but its png-files are not existing ... yet 
                        wget -q http://b-gp2-sc-201.imovetv.com/dishads/${dd[$j]} -O ./${dd[$j]} > /dev/null ;
			chmod 777 ${dd[$j]} ;

                	# make pictures for the file
			ffmpeg -i "./${dd[$j]}" -vf fps=1 ./snapshot-%4d.png

			# remove the original
			rm ${dd[$j]} ;

			# get the number of pictures and move them onto Isilon
			pp=(`echo "ls -1 ./*.png" | sort`) ;
			ppnr=${#pp[@]} ;
			ll=0 ;
			while [ "$ll" -lt "$ppnr" ] ; 
        		do
                        	echo "put ./${pp[$ll]} ./png/${clipbase}/${pp[$ll]}" | sudo sftp -i /home/ubuntu/.ssh/jn_dev2.pem dishads@d-gp2-sftp-1.imovetv.com ;
				# remove the local pic
				rm ./${pp[$ll]} ;
				(( ll = ll + 1 )) ;
			done ;

			# get out of the local folder
			popd ; 

		fi

        	(( j = j + 1 )) ;
	done ;
popd ;


# remove the lock:
rm -f $LOCK_FILE ; 
