#!/bin/bash

# get each file
today=`date +%Y%m%d` ;
rm /home/ubuntu/bin/SyncServer/ctrl/results/${today}/ti_ms ;mkdir /home/ubuntu/bin/SyncServer/ctrl/results/${today} ;
a=`cat /home/ubuntu/bin/ctrl/results | cut -d',' -f2 | sort | uniq ` ; 
for i in $a ; 
do 
	pushd /home/ubuntu/bin/SyncServer/ctrl/ > /dev/null ; 
	cut -d',' -f1- ../../ctrl/results | sed -s s#00000000#${today}#g | grep ${i} | ./filter.php -fbest-ad-match | ./filter.php -fmin-intro-length | cut -d',' -f1-  ; 
	popd > /dev/null ; 
done

# cleanup
# rm -f ${1} ;
# rm -f ${1}.pcm ;
